export const actions = {
    STORE_PENDING: "STORE_PENDING",
    SET_LEVEL: "SET_DIFFICULTY",
    SET_BOARD: "SET_BOARD",
    END_ON_FIRST_MOVE: "END_FIRST",
    FINISH_GAME: "FINISH",
    REVEAL_FIRST_TILE: "REVEAL_FIRST",
    REVEAL_TILE: "REVEAL",
    FLAG_AND_CHECK: "FLAG_AND_CHECK",
    FLAG_FIRST_MOVE: "FLAG_FIRST",
    FLAG_TILE: "FLAG",
    GAME_WON: "WON_GAME",
    UPDATE_BOARD: "UPDATE_BOARD",
    FETCH_PENDING_GAME: "FETCH_PENDING_GAME"
}




